/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffms;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author sepich
 */
public class DeductionStaff extends javax.swing.JInternalFrame {
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst = null;

    /**
     * Creates new form DeductionStaff
     */
    public DeductionStaff() {
        initComponents();
        conn = dbConnect.connectDB();
        lbl_emp.setText(String.valueOf(Employee.empId).toString());
        
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jComboBoxSelected = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_staffid = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_designation = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        txt_datehired = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        r_percentage = new javax.swing.JRadioButton();
        r_amount = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_percentage = new javax.swing.JTextField();
        txt_amount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_dateofbirth = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_jobtitle = new javax.swing.JTextField();
        txt_basesalary = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_reason = new javax.swing.JTextField();
        jSave = new javax.swing.JButton();
        jCalculate = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_sal = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Staff :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 23, -1, -1));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 18, 170, -1));

        jComboBoxSelected.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jComboBoxSelected.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "first_name", "last_name", " " }));
        jPanel1.add(jComboBoxSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 18, 171, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Staff Information"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Staff ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 29, -1, -1));

        jLabel3.setText("First Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 61, -1, -1));

        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 93, -1, -1));

        jLabel5.setText("Designation:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 29, -1, -1));

        jLabel6.setText("Status:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 61, -1, -1));

        jLabel7.setText("Date Hired:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 93, -1, -1));
        jPanel2.add(txt_staffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 24, 172, -1));
        jPanel2.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 56, 172, -1));
        jPanel2.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 88, 172, -1));
        jPanel2.add(txt_designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 24, 173, -1));
        jPanel2.add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 56, 173, -1));

        txt_datehired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_datehiredActionPerformed(evt);
            }
        });
        jPanel2.add(txt_datehired, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 88, 173, -1));

        jLabel8.setText("Update Salary by:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 194, -1, -1));

        r_percentage.setText("Percentage(%)");
        r_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_percentageActionPerformed(evt);
            }
        });
        jPanel2.add(r_percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 190, -1, -1));

        r_amount.setText("Amount");
        r_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_amountActionPerformed(evt);
            }
        });
        jPanel2.add(r_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 190, -1, -1));

        jLabel9.setText("Percentage:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 224, -1, -1));

        jLabel10.setText("Amount:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 224, -1, -1));
        jPanel2.add(txt_percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 219, 95, -1));
        jPanel2.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 219, 95, -1));

        jLabel11.setText("Date of Birth:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 125, -1, -1));

        jLabel12.setText("Department:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 157, -1, -1));

        jLabel13.setText("Job Title:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 125, -1, -1));

        jLabel14.setText("Base Salary:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 152, -1, -1));
        jPanel2.add(txt_dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 120, 172, -1));
        jPanel2.add(txt_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 152, 172, -1));

        txt_jobtitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jobtitleActionPerformed(evt);
            }
        });
        jPanel2.add(txt_jobtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 120, 173, -1));
        jPanel2.add(txt_basesalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 152, 173, -1));

        jLabel15.setText("Reason:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 256, -1, -1));
        jPanel2.add(txt_reason, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 251, 176, -1));

        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });
        jPanel2.add(jSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 283, 97, -1));

        jCalculate.setText("Calculate");
        jCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalculateActionPerformed(evt);
            }
        });
        jPanel2.add(jCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 283, -1, -1));

        jClear.setText("Clear");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });
        jPanel2.add(jClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 283, 102, -1));

        jLabel16.setFont(jLabel16.getFont().deriveFont(jLabel16.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel16.setText("Total Deduction:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 194, -1, -1));

        jLabel17.setFont(jLabel17.getFont().deriveFont(jLabel17.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel17.setText("Salary After Deduction :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 224, -1, -1));

        lbl_total.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_total.setText("0.00");
        jPanel2.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 193, -1, -1));

        lbl_sal.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl_sal.setText("0.00");
        jPanel2.add(lbl_sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 223, -1, -1));

        jLabel18.setText("Logged In As:");

        lbl_emp.setText("emp");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Deduction Table"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_emp))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(lbl_emp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void loadDataToTable(){
        try{
            String query = "select * from Deductions";
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst.close();
            rs.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        try{
//            Class.forName("org.sqlite.JDBC");
//            Connection conn = DriverManager.getConnection("jdbc:sqlite:/Users/sepich/NetBeansProjects/StaffManagementSystem/mydatabase.sqlite");
                //String sql = "select * from Staff_Information where id=? ";
            String selection = (String) jComboBoxSelected.getSelectedItem();
            String query = "select * from Staff_Information where "+selection+"=? ";
            
            pst = conn.prepareStatement(query);
            pst.setString(1, txt_search.getText());
            rs = pst.executeQuery();

            String add1 = rs.getString("id");
            txt_staffid.setText(add1);

            String add2 = rs.getString("first_name");
            txt_firstname.setText(add2);

            String add3 = rs.getString("last_name");
            txt_lastname.setText(add3);

            String add4 = rs.getString("date_of_birth");
            txt_dateofbirth.setText(add4);

            String add5 = rs.getString("department");
            txt_department.setText(add5);

            String add6 = rs.getString("basic_salary");
            txt_basesalary.setText(add6);

            String add7 = rs.getString("status");
            txt_status.setText(add7);

            String add8 = rs.getString("job_title");
            txt_jobtitle.setText(add8);

            String add9 = rs.getString("date_hier");
            txt_datehired.setText(add9);

            // String add10 = rs.getString("Designation");
            //txt_designation.setText(add10);

        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "No Data Connetion");
        }
        finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_datehiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_datehiredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_datehiredActionPerformed

    private void r_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_percentageActionPerformed
        // TODO add your handling code here:
        r_percentage.setSelected(true);
        r_amount.setSelected(false);

        txt_amount.setEnabled(false);
        txt_percentage.setEditable(true);
        txt_percentage.setEnabled(true);
        txt_amount.setText("");
    }//GEN-LAST:event_r_percentageActionPerformed

    private void r_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_amountActionPerformed
        // TODO add your handling code here:
        r_amount.setSelected(true);
        r_percentage.setSelected(false);

        txt_percentage.setEnabled(false);
        txt_amount.setEditable(true);
        txt_amount.setEnabled(true);
        txt_percentage.setText("");
    }//GEN-LAST:event_r_amountActionPerformed

    private void txt_jobtitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jobtitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jobtitleActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?", "Add Record",JOptionPane.YES_NO_OPTION);
        if(confirm == 0){
            String value3 = lbl_emp.getText();
            try{
//                Class.forName("org.sqlite.JDBC");
//                Connection conn = DriverManager.getConnection("jdbc:sqlite:/Users/sepich/NetBeansProjects/StaffManagementSystem/mydatabase.sqlite");
                String sql = "insert into Deductions (first_name,last_name,salary,deduction_amount,deduction_reason,staff_id,made_by) values (?,?,?,?,?,?,'"+value3+"') ";
                pst = conn.prepareStatement(sql);

                pst.setString(1,txt_firstname.getText());
                pst.setString(2,txt_lastname.getText());
                pst.setString(3,txt_basesalary.getText());
                pst.setString(4,lbl_total.getText());
                pst.setString(5,txt_reason.getText());
                pst.setString(6,txt_staffid.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);

            }
            finally{
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e){
                }
            }

        }
    }//GEN-LAST:event_jSaveActionPerformed

    private void jCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalculateActionPerformed
        // TODO add your handling code here:
        int salary = Integer.parseInt(txt_basesalary.getText());

        if(r_percentage.isSelected() == true){
            int percentage = Integer.parseInt(txt_percentage.getText());
            //calculate the totall hours of overtime
            int total_percentage_deduction = salary/100*percentage;
            String x = String.valueOf(total_percentage_deduction);
            int sal = salary - total_percentage_deduction;
            lbl_total.setText(x);
            lbl_sal.setText(String.valueOf(sal));
        }
        if(r_amount.isSelected() == true){
            int deduction = Integer.parseInt(txt_amount.getText());
            //calculate the total hours of overtime
            int total_amount_deduction = salary - deduction;
            String s = String.valueOf(total_amount_deduction);

            lbl_sal.setText(s);
            lbl_total.setText(String.valueOf(deduction));

        }
    }//GEN-LAST:event_jCalculateActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
        txt_staffid.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_dateofbirth.setText("");
        txt_department.setText("");
        txt_status.setText("");
        txt_basesalary.setText("");
        txt_jobtitle.setText("");
        txt_datehired.setText("");
        txt_reason.setText("");
        txt_percentage.setText("");
        txt_amount.setText("");
        txt_search.setText("");
        lbl_total.setText("");
        lbl_sal.setText("");

    }//GEN-LAST:event_jClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCalculate;
    private javax.swing.JButton jClear;
    private javax.swing.JComboBox<String> jComboBoxSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JLabel lbl_sal;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JRadioButton r_amount;
    private javax.swing.JRadioButton r_percentage;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_basesalary;
    private javax.swing.JTextField txt_datehired;
    private javax.swing.JTextField txt_dateofbirth;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_jobtitle;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_percentage;
    private javax.swing.JTextField txt_reason;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_staffid;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
}
