/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffms;

/**
 *
 * @author sepich
 */
public class staffReportForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form staffReportForm
     */
    public staffReportForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonStaffInformation = new javax.swing.JButton();
        jButtonAllowance = new javax.swing.JButton();
        jButtonDeduction = new javax.swing.JButton();

        setClosable(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wellcome.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Report Form");

        jButtonStaffInformation.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonStaffInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/staffReport.png"))); // NOI18N
        jButtonStaffInformation.setText("Staff Information");
        jButtonStaffInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStaffInformationActionPerformed(evt);
            }
        });

        jButtonAllowance.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonAllowance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/allowence.png"))); // NOI18N
        jButtonAllowance.setText("Allowance");
        jButtonAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllowanceActionPerformed(evt);
            }
        });

        jButtonDeduction.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButtonDeduction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deduction.png"))); // NOI18N
        jButtonDeduction.setText("Deduction");
        jButtonDeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeductionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonStaffInformation)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDeduction))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStaffInformation)
                    .addComponent(jButtonAllowance)
                    .addComponent(jButtonDeduction))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStaffInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStaffInformationActionPerformed
        // TODO add your handling code here:
        reportCode obj = new reportCode();
        obj.StaffReport();
    }//GEN-LAST:event_jButtonStaffInformationActionPerformed

    private void jButtonAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllowanceActionPerformed
        // TODO add your handling code here:
        reportCode obj = new reportCode();
        obj.AllowanceReport();
    }//GEN-LAST:event_jButtonAllowanceActionPerformed

    private void jButtonDeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeductionActionPerformed
        // TODO add your handling code here:
        reportCode obj = new reportCode();
        obj.DeductionReport();
    }//GEN-LAST:event_jButtonDeductionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAllowance;
    private javax.swing.JButton jButtonDeduction;
    private javax.swing.JButton jButtonStaffInformation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
